### ISSUE TITLE
Blank screen after deleting a scale color 

### ISSUE THREAD

**Issue by damidina** [primer/prism#35] opened 2022-06-21 17:10 UTC
**Describe the bug**
When I select a scale and delete a color the page goes blank

**To Reproduce**
1. Go to prism
2. Create a new palette or go to an existing palette 
3. Select an existing scale or add a new sacle 
4. On the right panel select delete color for the scale (screenshot below)

<img width="297" alt="image" src="https://user-images.githubusercontent.com/2275314/174857889-e0d97975-fec0-4718-bd68-ec3c111105dd.png">

**Expected behavior**
Not exactly sure but the page probably shouldn't go blank

**Screenshots**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2275314/174858173-bb3f7161-ebfb-40f4-8616-9489541c5126.png">
<img width="766" alt="image" src="https://user-images.githubusercontent.com/2275314/174858216-779076ef-0078-4bd9-8600-f4b82c412c5d.png">

**Environment**
Chrome Version 102.0.5005.115 (Official Build) (x86_64)
Mac OS Catalina - Version 10.15.7

**Additional context**
Posted a video here: https://twitter.com/DamiDina/status/1539291589847171073

**Comment by colebemis** [comment] 2022-06-21 17:31
Looks like it only breaks when deleting the last color in the scale. @pavelkeyzik I think this is related to the bug your reported and fixed: https://github.com/primer/prism/issues/10

@pavelkeyzik Could you disable the "Delete color" button if the color is the last color in the scale?

**Comment by pavelkeyzik** [comment] 2022-06-21 21:31
@damidina The issue should be resolved. You can try to reproduce it again. If you're happy with the result, you can close the issue. If not, just let us know 😊

**Closed** 2022-06-22 22:37 UTC
Labels: bug
